name: l3bi-r-2026
# from plasmabio-template-r adapted for demo-r
# janvier 2026

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
# defaults changÃ© en nodefaults pour construire l'env sur Mydocker de Saclay, janvier 2025
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7.4,<8
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar-text >=1.1.0,<2
  - nodejs>=20
 
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - jupyterlab-variableinspector
    # https://github.com/lckr/jupyterlab-variableInspector
  - nbresuse
  - libgomp
  
  # R environment (version for Ubuntu 24.04)
  - r-irkernel>1.3
  - r-base>=4.3
  - r-tidyverse
  - r-essentials
  - r-repr

  # Build tools required for Ubuntu 24.04
  - gxx_linux-64
  - gcc_linux-64
  - gfortran_linux-64

  # R packages
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-ggplot2
  - r-writexl
  - r-readxl
  - r-rcolorbrewer
  
  # JupyterLab Variable inspector
  - pip
  - pip:
    - watermark
    - matplotlib
  
